"""Generates verification_log.md: one current-state table (every row), one discrepancy table, counts computed."""
from .rows import CAP, CAP_SOURCES
from .schema import LEDGER_ASOF
from .verification import VERIFY, DISCREPANCIES

STATUSES = ["VERIFIED", "VERIFIED (external)", "PARTIAL", "CORRECTED"]


def _c(t, n=None):
    t = str(t).replace("|", "/").replace("\n", " ")
    if n and len(t) > n:
        t = t[:n].rsplit(" ", 1)[0].rstrip(",;. ") + " [...]"
    return t


def log_rows(events, legal):
    """[(set, id, status, pin, evidence)] in table order: kinetic, non-kinetic, legal, capabilities."""
    out = []
    for dom, name in (("kinetic", "kinetic"), ("non_kinetic", "non-kinetic")):
        for r in sorted((e for e in events if e["domain"] == dom), key=lambda r: r.get("date") or r["start"]):
            out.append((name, r["id"], r["pin"]))
    out += [("legal", r["id"], r["citation"]) for r in sorted(legal, key=lambda r: r["start"])]
    out += [("capability", c, CAP_SOURCES[c]) for c in CAP]
    return [(s, i, VERIFY[i][0], _c(p, 110), _c(VERIFY[i][1])) for s, i, p in out]


def counts(rows):
    t = {}
    for s, _, st, _, _ in rows:
        t.setdefault(s, dict.fromkeys(STATUSES, 0))[st] += 1
    return t


def render(events, legal):
    rows = log_rows(events, legal)
    cnt = counts(rows)
    n = {s: sum(v.values()) for s, v in cnt.items()}
    total = len(rows)
    partial = [i for s, i, st, _, _ in rows if st == "PARTIAL"]
    o = []
    a = o.append
    a("# Counterspace Ledger: Verification Log")
    a("")
    a("*As of %s. Generated by `python3 tools/build_data.py` from the data files and `tools/ledger/verification.py`; edit that file, not this page. "
      "Earlier passes and full-length evidence are in `verification_history.md`.*" % LEDGER_ASOF)
    a("")
    a("## Contents")
    a("")
    a("1. [Summary](#1-summary)")
    a("2. [Method](#2-method)")
    a("3. [Current state of every row](#3-current-state-of-every-row)")
    a("4. [Open items](#4-open-items)")
    a("5. [Discrepancies found and fixed](#5-discrepancies-found-and-fixed)")
    a("")
    a("## 1. Summary")
    a("")
    a("- **Scope:** %d items = %d kinetic + %d non-kinetic rows (`data/events.json`), %d legal items (`data/legal.json`), %d capability categories (`data/capabilities.json`)." % (
        total, n["kinetic"], n["non-kinetic"], n["legal"], n["capability"]))
    a("- **Status:** every item is VERIFIED, VERIFIED (external) or CORRECTED, except %d PARTIAL (%s). None is UNCHECKED." % (
        len(partial), ", ".join("`%s`" % p for p in partial)))
    a("- **Discrepancies:** %d found and fixed in total ([section 5](#5-discrepancies-found-and-fixed))." % len(DISCREPANCIES))
    a("- **Automated:** `validate()` in `tools/build_data.py` fails the build if this table's ids, per-set counts or status totals differ from the data.")
    a("")
    a("| Set | Rows | VERIFIED | VERIFIED (external) | PARTIAL | CORRECTED |")
    a("|---|---|---|---|---|---|")
    order = ["kinetic", "non-kinetic", "legal", "capability"]
    for s in order:
        a("| %s | %d | %s |" % (s.capitalize() if s != "non-kinetic" else "Non-kinetic", n[s], " | ".join(str(cnt[s][x]) for x in STATUSES)))
    a("| **Total** | **%d** | %s |" % (total, " | ".join("**%d**" % sum(cnt[s][x] for s in order) for x in STATUSES)))
    a("")
    a("Each row counts once, under its status. CORRECTED means a defect was found, fixed in the builder, then re-verified.")
    a("")
    a("## 2. Method")
    a("")
    a("1. **SWF rows.** The SWF 2026 text extraction was searched programmatically and read by hand. Each row's date, value and pin were checked against the pinned PDF page; the printed section-page (for example `02-36`) was mapped to the PDF page by the page-footer label (e.g. PDF 72 = 01-23, PDF 149 = 02-36).")
    a("2. **Tables.** Tables 1-4, 4-1, 5-1 and 16-2 to 16-4 extract with scrambled columns in plain text, so they were read cell by cell with pdfplumber. Table 1-4 (PDF 72-73) has 33 rows: 32 are ledger rows and the 33rd, the US Delta 180 intercept of 5 Sep 1986, is co-orbital and excluded by the scope rule. Table 5-1 (PDF 212) lists 16 destructive tests: 5 direct-ascent (ledger rows) and 11 co-orbital (excluded).")
    a("3. **Non-SWF and legal rows.** Sources were fetched with WebFetch or curl or located by search. Where a site blocks bots (ICAO, UNOOSA, UN Digital Library, treaties.unoda.org, OUP), mirrors such as `documents.un.org` symbol access were tried; otherwise the fact was checked through a search snippet or another source, as the row says. No row is VERIFIED on inference or on a neighboring row.")
    a("4. **URLs.** Every distinct `source_url` was requested with curl and its landing page inspected, not only its status code.")
    a("5. **Capability matrix.** SWF's country matrix (Executive Summary, PDF pp. 22-32) was read from its vector shapes by position and colour (green none, yellow some, red significant, dark \"?\" uncertain, dash no data) across all 12 country tables. It has no cyber row. Pre-2020s cells are the builder's reconstruction, not SWF-assessed, and are labeled so on the chart.")
    a("")
    a("**Status vocabulary.** VERIFIED: the pinned page or fetched source shows the value. VERIFIED (external): checked against a named non-SWF source. PARTIAL: core fields verified; the named field is not isolable or comes from outside the pin. CORRECTED: a defect was found and fixed, then verified. UNCHECKED: not re-checked (no row carries it).")
    a("")
    a("## 3. Current state of every row")
    a("")
    a("Pins are copied from the data (`pin` for events, `citation` for legal items, the source text for capabilities). Evidence is a short quote or note; \"Disc. N\" refers to [section 5](#5-discrepancies-found-and-fixed). \"T1-4\" = Table 1-4, \"T5-1\" = Table 5-1.")
    a("")
    a("| set | id | status | pin | evidence |")
    a("|---|---|---|---|---|")
    for s, i, st, p, e in rows:
        a("| %s | `%s` | %s | %s | %s |" % (s, i, st, p, e))
    a("")
    a("## 4. Open items")
    a("")
    a("The %d PARTIAL items concern the 2020s \"developing\" (P) coding in Chart B, checked against SWF's country matrix (seven rows, four columns, no cyber row)." % len(partial))
    a("")
    a("| Item | Exactly what is unverified | Impact |")
    a("|---|---|---|")
    a("| `direct_ascent` | D entries (US, China, Russia, India) match the matrix. Of the 2020s P entries, Israel, Japan and Germany match (\"uncertain\" R&D); South Korea, Iran, North Korea and France show \"no data\", so those P entries are the builder's reading of the country chapters. | Chart B's 2020s count includes those four P states. No event, date or altitude depends on them. |")
    a("| `co_orbital` | D entries (Russia, US, China) match. France (\"some\" R&D) and Germany (\"uncertain\") match; India, Iran, Israel, Japan, North Korea and the UK show \"no data\". | Six P states in the 2020s count are the builder's judgment. No plotted event depends on them. |")
    a("")
    a("Follow-up for the page owner: drop those P states from `CAP` or label them on the chart as builder-assessed.")
    a("")
    a("## 5. Discrepancies found and fixed")
    a("")
    a("All %d were corrected in `tools/ledger/rows.py` (or the page text noted). Discrepancy 35 is superseded for Solwind by 40." % len(DISCREPANCIES))
    a("")
    a("| # | Row | Defect | Fix |")
    a("|---|---|---|---|")
    for d in DISCREPANCIES:
        a("| " + " | ".join(_c(x) for x in d) + " |")
    a("")
    return "\n".join(o)
