// scenes/configs/spaceplanes.js: scene `spaceplanes` (see ../config.js for the list order)
import { GEO_ALT, IS_PHONE, orbitPos } from '../core.js';
import { ellipsePath } from '../co-sim.js';
import { C, PK } from './shared.js';

// OTV-7's orbit as tracked by amateurs in Feb. 2024 (SWF p. 01-06): 323 x 38,838 km at 59.1 deg. Node and argument of perigee are illustrative.
const HEO_ORBIT = { perigee: 323, apogee: 38838, inc: 59.1, raan: 110, argp: 270, m0: 3.2, revs: 3.4 };
const MX = IS_PHONE ? 66 : 112; // spaceplane model size cap (px): smaller on a phone so a craft never sits oversized on the limb

export const SPACEPLANES = {
  id: 'spaceplanes',
  date: '2023-12-28',
  title: 'Spaceplanes: X-37B and China’s reusable craft (2010–2026)',
  shells: [],
  duration: 32,
  caption:
    'Since 2010 the US X-37B spaceplane, a reusable uncrewed spacecraft that lands on a runway, has flown eight missions (OTV-1 to OTV-8, for Orbital Test Vehicle). ' +
    'Six lasted 224 to 908 days. OTV-7 flew in an orbit reaching 38,838 km, and OTV-8 launched in August 2025. ' +
    'China’s reusable experimental spacecraft (CSSHQ) has flown three missions, lasting 2 to 276 days, and a fourth launched in February 2026. After flights 2 and 3 it repeatedly approached objects that the space-tracking catalog lists as released from it. ' +
    'The Secure World Foundation (SWF), a space-security nonprofit, says the X-37B has so far approached no other object. The purposes of the missions are not stated. ' +
    'A 2019 analysis by China’s People’s Liberation Army (PLA), as SWF reports it, warned that the X-37B could turn into an “aggressive” fighter in space. ' +
    'No treaty or resolution on this page’s law timeline is tied to these flights.',
  cite: 'Secure World Foundation, 2026: Table 1-1 (p. 01-08), Figure 1-3 (p. 01-07), pp. 01-04 to 01-09; Table 3-1 (p. 03-08), pp. 03-06 to 03-08.',
  related: null,
  event: 'us-2023-otv7',
  inset: 'Top view',
  scaleNote: 'The distances to the released objects are exaggerated and orbital motion is slowed.',
  anchors: {
    us: { orbit: { alt: 350, inc: 45, raan: 288, u0: 0.47, du: 3.4 } },
    heo: { ellipse: HEO_ORBIT },
    cn: { orbit: { alt: 600, inc: 50, raan: 250, u0: 1.0, du: 2.0 } },
  },
  acts: [
    { t0: 0, t1: 0.3, cam: 1 },
    { t0: 0.3, t1: 0.54, cam: 2 },
    { t0: 0.54, t1: 1, cam: 3 },
  ],
  actors: [
    // ---- US X-37B, OTV-1 to OTV-6: LEO flights
    { type: 'path', fn: (u) => orbitPos(350, 38, 288, u * 2 * Math.PI), N: 120, color: '#8fd0ff', opacity: 0.6, thick: 0.002, fade: true, acts: [0], staticKeep: false },
    {
      type: 'path',
      fn: (u) => orbitPos(350, 54, 288, u * 2 * Math.PI),
      N: 120,
      color: '#8fd0ff',
      opacity: 0.6,
      thick: 0.002,
      fade: true,
      acts: [0],
      staticHide: true,
      staticKeep: false,
    },
    { type: 'path', fn: (u) => orbitPos(350, 45, 288, u * 2 * Math.PI), N: 120, color: C.us, opacity: 0.85, thick: 0.0028, fade: true, acts: [0], push: 0.1 },
    {
      type: 'craft',
      id: 'x37',
      minPx: IS_PHONE ? 52 : 76,
      maxPx: MX,
      anchor: 'us',
      acts: [0],
      model: 'plane',
      color: C.us,
      bright: true,
      scale: 2.2 * PK,
      label: 'X-37B (US)',
      short: 'X-37B',
      dx: 46,
      dy: -34,
      key: [
        [0, 0, 0, 0],
        [1, 0, 0, 0],
      ],
    },
    { type: 'trail', craft: 'x37', t0: 0.0, t1: 0.3, color: C.us, acts: [0], thick: 0.003 },
    // ---- US X-37B, OTV-7: highly elliptical orbit
    {
      type: 'path',
      fn: (u) => orbitPos(GEO_ALT, 0, 0, u * 2 * Math.PI),
      N: 120,
      color: C.geo,
      opacity: 0.6,
      thick: 0.0024,
      fade: true,
      acts: [1],
      push: 0.15,
      label: 'GEO ring (35,786 km)',
      short: 'GEO',
      opt: true,
      staticHide: true,
      labelIdx: 92,
      dx: 20,
      dy: 20,
    },
    {
      type: 'path',
      points: ellipsePath(HEO_ORBIT, 360),
      color: C.us,
      opacity: 0.8,
      thick: 0.0026,
      fade: true,
      acts: [1],
      push: 0.15,
      label: 'OTV-7 orbit: 323 to 38,838 km up, tilt 59.1° (Feb. 2024)',
      short: 'OTV-7 orbit',
      labelIdx: 180,
      dx: 40,
      dy: -20,
    },
    {
      type: 'craft',
      id: 'x37h',
      minPx: IS_PHONE ? 52 : 76,
      maxPx: MX,
      anchor: 'heo',
      acts: [1],
      model: 'plane',
      color: C.us,
      bright: true,
      scale: 3.1 * PK,
      label: 'X-37B OTV-7 (US)',
      short: 'OTV-7',
      dx: -60,
      dy: 34,
      key: [
        [0, 0, 0, 0],
        [1, 0, 0, 0],
      ],
    },
    { type: 'trail', craft: 'x37h', t0: 0.24, t1: 0.54, N: 160, color: C.us, acts: [1], thick: 0.003 },
    // ---- China, CSSHQ: flights 2 and 3 and the objects released from them
    {
      type: 'path',
      fn: (u) => orbitPos(600, 50, 250, u * 2 * Math.PI),
      N: 120,
      color: C.cn,
      opacity: 0.55,
      thick: 0.002,
      fade: true,
      acts: [2],
      push: 0.1,
      label: 'CSSHQ orbit: about 600 km, 50° (SWF)',
      short: '~600 km · 50°',
      opt: true,
      staticHide: true,
      staticKeep: false,
      labelIdx: 30,
      dx: 30,
      dy: -30,
    },
    {
      type: 'craft',
      id: 'csshq',
      variant: 'winged', // a generic winged vehicle: the sources show no more, so it is not drawn as an X-37B
      minPx: IS_PHONE ? 38 : 54,
      maxPx: IS_PHONE ? 52 : 76,
      anchor: 'cn',
      acts: [2],
      model: 'plane',
      color: C.cn,
      bright: true,
      scale: 0.55 * PK,
      label: 'CSSHQ (China)',
      short: 'CSSHQ',
      dx: 36,
      dy: -66,
      staticAt: [0.1, 0.27],
      labelFn: (t, n) => (t < 0.765 ? (n ? 'CSSHQ flight 2' : 'CSSHQ flight' + ' 2 (China)') : n ? 'CSSHQ flight 3' : 'CSSHQ flight 3 (China)'),
      key: [
        [0.54, 0, 0, 0],
        [1, 0, 0, 0],
      ],
    },
    {
      type: 'craft',
      id: 'objJ',
      minPx: IS_PHONE ? 48 : 56,
      maxPx: IS_PHONE ? 72 : 84,
      anchor: 'cn',
      acts: [2],
      vis: [0.585, 0.755],
      small: true,
      scale: 1.6 * PK,
      color: C.cn,
      label: 'Released object J',
      short: 'Obj. J',
      dx: -58,
      dy: 46,
      staticAt: [0.1, 0.46],
      key: [
        [0.585, 0, 0, 0],
        [0.605, 0.1, 0.01, 0.02],
        [0.625, 0.2, 0.012, 0.03],
        [0.64, 0.062, 0, 0],
        [0.655, 0.2, 0.012, 0.03],
        [0.676, 0.062, 0, 0],
        [0.69, 0.21, 0, 0.03],
        [0.72, 0.075, 0.004, 0.01],
        [0.735, 0.18, 0.01, 0.03],
        [0.755, 0.16, 0.01, 0.03],
      ],
    },
    { type: 'link', a: 'csshq', b: 'objJ', t0: 0.635, t1: 0.647, color: '#fff1c1', width: 0.009 },
    { type: 'link', a: 'csshq', b: 'objJ', t0: 0.671, t1: 0.683, color: '#fff1c1', width: 0.009 },
    {
      type: 'craft',
      id: 'objG',
      minPx: IS_PHONE ? 48 : 56,
      maxPx: IS_PHONE ? 72 : 84,
      anchor: 'cn',
      acts: [2],
      vis: [0.8, 0.985],
      small: true,
      scale: 1.6 * PK,
      color: C.cn,
      label: 'Released object G',
      short: 'Obj. G',
      dx: -46,
      dy: 20,
      staticAt: [0.1, 0.7],
      key: [
        [0.8, 0, 0, 0],
        [0.815, 0.09, 0.01, 0.03],
        [0.86, 0.24, 0.02, 0.04],
        [0.895, 0.08, 0.005, 0.02],
        [0.93, 0.1, 0.005, 0.02],
        [0.96, 0.08, 0.005, 0.02],
      ],
    },
    { type: 'trail', craft: 'csshq', t0: 0.54, t1: 1, color: C.cn, acts: [2], thick: 0.0018, tail: 0.12, wakeOp: 0.2, taper: 0.1 }, // a soft wake: thin at its tail, faint, capped in length
    { type: 'trail', craft: 'objJ', t0: 0.585, t1: 0.755, until: 0.82, color: C.cn, acts: [2], thick: 0.0022, tail: 0.25, wakeOp: 0.4 }, // the wake ends soon after Object J does
    { type: 'trail', craft: 'objG', t0: 0.8, t1: 0.985, color: C.cn, acts: [2], thick: 0.0022, tail: 0.25, wakeOp: 0.4 },
  ],
  fillK: 0.5,
  cloudK: 1.2,
  cloudFloor: 0.8, // a cloud layer stays on the Earth even in the close China views, so it is not a flat tan
  sunView: { az: -22, el: 20 }, // the lit side faces the opening camera: the China episode is in daylight, not a grey night
  lightsK: 0.2, // the night city lights are dimmed so they never blow out into white blobs under the labels
  nightK: 1.5, // a modest night ambient: enough to read the terrain without a grey haze over the dark side
  atmoK: 0.6, // less atmosphere haze on the limb
  insetSizePhone: [84, 72], // 375: a small Top view, in the lower left, off the limb and clear of the craft
  insetCornerPhone: 'bl',
  phoneHide: ['GEO', 'OTV-7 orbit', 'CSSHQ orbit', '~600'], // 375: at most two labels over the picture
  still: 0.5,
  stillCam: { at: [36, 20, 7.2], look: [0, 0, 0], hideShell: true },
  captionShort: true, // the picture's caption is the short text at every width; the step list keeps the full sentence
  status: [
    [0, 'X-37B, OTV-1 to OTV-6 (2010–2022): flights of 224, 469, 675, 718, 780 and 908 days (SWF)', 'X-37B OTV-1 to 6: 224 to 908 days'],
    [0.1, 'SWF: X-37B orbits were 300–400 km up, tilted 38°–54° to the equator (hobbyist tracking)', '300–400 km, tilt 38°–54° (SWF)'],
    [0.2, 'Runway landings: Vandenberg AFB (OTV-1 to OTV-3) and Kennedy Space Center (OTV-4 to OTV-6)', 'Landings: Vandenberg, then Kennedy'],
    [0.26, 'SWF: to date the X-37B “has not approached nor rendezvoused with any other space objects”', 'SWF: X-37B approached no other object'],
    [0.3, 'OTV-7 (launched 28 Dec. 2023): an elongated orbit, 323 to 38,838 km up, tilt 59.1° (Feb. 2024)', 'OTV-7: 323 to 38,838 km up, tilt 59.1°'],
    [0.38, 'SWF: may have tested a new sensor or payload; what and why are unclear', 'SWF: purpose and payload unclear'],
    [0.46, 'Oct. 2024: uses air drag to lower its orbit; landed at Vandenberg 7 Mar. 2025 (434 days)', 'Landed 7 Mar. 2025 after 434 days'],
    [0.51, 'OTV-8 launched 21 Aug. 2025; SWF says it was still in orbit in Feb. 2026', 'OTV-8 launched 21 Aug. 2025'],
    [0.54, 'China’s CSSHQ: flights of 2, 276 and 268 days; a fourth launched 6 Feb. 2026 (SWF)', 'CSSHQ: flights of 2, 276, 268 days'],
    [0.56, 'Flight 1 (launched 4 Sept. 2020) spent 2 days in orbit', 'CSSHQ flight 1: 2 days in orbit'],
    [0.575, 'Flight 2 (2022–23): orbit raised to about 597–607 km; Object J cataloged, apparently released', 'Flight 2: Object J apparently released'],
    [0.625, 'LeoLabs: approaches to Object J, “[at] least two and possibly three capture/docking operations”', 'LeoLabs: approaches to Object J'],
    [0.76, 'Flight 3 (2023–24): Object G released 24 May 2024; approaches in June, within 1 km on 12 June', 'Flight 3: Object G released 24 May 2024'],
    [
      0.86,
      'A 2019 PLA analysis (not SWF’s view): ' + 'the X-37B could become an “aggressive unmanned intelligent fighter”',
      'A 2019 PLA analysis, not SWF’s view',
    ],
    [0.93, 'SWF: Chinese concern about the X-37B is thought to have driven China to build its own spaceplane', 'SWF: X-37B thought to have driven CSSHQ'],
    [0.975, 'Flight 4 launched from Jiuquan on 6 Feb. 2026; SWF reports no landing yet', 'Flight 4 launched 6 Feb. 2026'],
  ],
  cameras: [
    { name: 'All three parts', auto: true, at: [40, -25, 4.4], phone: { at: [40, -25, 5.2] } },
    {
      name: 'X-37B: flights in low Earth orbit',
      chip: 'X-37B low-orbit flights',
      act: 0,
      fitCraft: { anchor: 'us', ids: ['x37'], dir: [-0.5, 0.55, 0.7], dMin: 1.1, fill: 0.75, t: 0.15 },
    },
    {
      name: 'X-37B OTV-7: follows the craft',
      chip: 'X-37B OTV-7',
      act: 1,
      fitCraft: { anchor: 'heo', ids: ['x37h'], dir: [-0.6, 0.7, 0.6], dMin: 2.3, fill: 1.1, t: 0.42, lock: true, tight: true },
    },
    {
      name: 'China: CSSHQ and released objects',
      chip: 'China CSSHQ',
      act: 2,
      fitCraft: { anchor: 'cn', ids: ['csshq', 'objJ', 'objG'], dir: [-0.3, 0.6, 0.75], phoneDir: [-0.25, 1.15, 0.45], fill: 0.93, dMin: 0.1, t: 0.75 },
    },
    // unlocked from the tour
    { name: 'Whole scene: Earth and every orbit', at: [32, -25, 5.8], phone: { at: [32, -25, 8] }, ref: false, hide: ['OTV-7 orbit'] },
  ],
  staticCenter: [40, 105],
  staticFit: 1.6,
  staticFitPhone: 1.3,
  staticKeyClearPhone: true, // 375 static: the legend key sits below the Earth, not on it
  staticSnap: { csshq: [0.6], objJ: [0.605], objG: [0.93] },
  staticLabels: { csshq: 'CSSHQ + Obj. J, G' },
  staticLabelsNarrow: { csshq: 'CSSHQ' }, // the phone key already reads "CSSHQ, Obj. J, G"
  staticNoLabel: ['objJ', 'objG'], // the static key names them: one label for the China group, not three stacked on the limb
  staticCraftScale: { csshq: 0.78 },
  staticKey: [
    [C.us, 'US X-37B: low Earth orbit flights, OTV-7 orbit', 'X-37B orbits'],
    [C.geo, 'GEO ring (35,786 km)', 'GEO ring'],
    [C.cn, 'China: CSSHQ and released objects J, G', 'CSSHQ, Obj. J, G'],
  ],
  staticStatusPhone: 'X-37B: eight flights since 2010; CSSHQ: three flights, a fourth launched Feb. 2026',
  staticStatus: 'US X-37B: eight flights since 2010, OTV-7 reaching 38,838 km; China’s CSSHQ: three flights, a fourth launched Feb. 2026',
};
