// ============================================================================
// scenes/config.js: scene configuration data: palette, the SCENES (ten kinetic/non-kinetic plus three co-orbital) and the HERO overview
// ============================================================================
// ---------------------------------------------------------------- configs
import { GEO_ALT, IS_PHONE, orbitPos } from './core.js';
import { ellipsePath } from './co-sim.js';

// Actor colours follow the page palette (US, Russia, China); UK and defunct objects are neutral.
export const C = {
  us: '#56B4E9',
  ru: '#FF8C5A',
  cn: '#F0C24B',
  dead: '#9aa3b5',
  tgt: '#ffd166',
  int: '#ff6b6b',
  debris: '#ffb38a',
  iss: '#8cc8ff',
  gps: '#9be7c4',
  jam: '#ff5d5d',
  ok: '#6ee7a8',
  laser: '#ff4fd8',
  geo: '#ffcf6e',
  belt: '#b28cff',
  ground: '#e9edf7',
};

// OTV-7's orbit as tracked by amateurs in Feb. 2024 (SWF p. 01-06): 323 x 38,838 km at 59.1 deg. Node and argument of perigee are illustrative.
// Spacecraft models are drawn larger on phones (PK) so they stay legible in the small stage.
const PK = IS_PHONE ? 1.5 : 1;
const MX = IS_PHONE ? 58 : 86; // spaceplane model size cap (px): smaller on a phone so a craft never sits oversized on the limb
const HEO_ORBIT = { perigee: 323, apogee: 38838, inc: 59.1, raan: 110, argp: 270, m0: 3.2, revs: 3.4 };

// SJ-21 presets that show the docked pair carry this note: SWF says SJ-21 "docked" with Compass G2 but does not describe any arm or grapple.
const ARM_TAG = { tag: 'Arm: not shown (SWF does not describe the mechanism)', tagShort: 'Arm: not shown (not in SWF)' };

export const SCENES = [
  {
    id: 'starfish',
    date: '1962-07-09',
    title: 'Starfish Prime (1962)',
    shells: ['LEO'],
    duration: 14,
    caption:
      'A 1.4-megaton warhead detonates about 400 km above Johnston Island. Electrons from the blast are trapped ' +
      'by Earth’s magnetic field. They spread' +
      ' along field lines and drift around the planet, forming an artificial radiation belt. SWF says such tests are known to have generated effects that' +
      ' damaged or destroyed satellites in orbit at the time. The belt’s spread in the animation is drawn for legibility, not computed.',
    cite: 'DOE/NV-209 Rev. 16 (Starfish Prime, 9 July 1962); SWF 2026, p. 12-05 (effects that damaged or destroyed satellites in orbit at the time).',
    related: 'ltbt-1963',
    event: 'us-1962-starfish-prime',
    actors: [
      { type: 'site', at: [16.7, -169.5], label: 'Johnston Island', short: 'Johnston Is.', color: C.ground, dx: -84, dy: 40 },
      {
        type: 'suborbital',
        from: [16.7, -169.5],
        to: [16.5, -169.0],
        apex: 400,
        t0: 0.02,
        t1: 0.14,
        color: C.int,
        label: 'Thor launch',
        opt: true,
        dx: -96,
        dy: 4,
      },
      { type: 'flash', at: [16.5, -169.2, 400], t0: 0.14, color: '#fff3c4', label: 'Detonation ~400 km', short: 'Detonation', dx: 34, dy: -34 },
      { type: 'field', lon: -169.2, Ls: [1.18, 1.4, 1.7], color: '#c9b0ff', t0: 0.14 },
      {
        type: 'belt',
        at: [16.5, -169.2],
        L: [1.12, 1.7],
        t0: 0.18,
        t1: 0.9,
        count: 2600,
        color: C.belt,
        size: 0.02,
        nLon: 12,
        label: 'Artificial radiation belt',
        short: 'Radiation belt',
      },
      {
        type: 'ring',
        alt: 800,
        inc: 44.8,
        raan: 40,
        color: '#8cc8ff',
        sat: {
          phase: 1.05,
          speed: 0.25,
          big: 1.5,
          label: 'Satellite in belt',
          short: 'Satellite',
          dx: 30,
          dy: 60,
          fail: { t: 0.8, label: 'Satellite damaged (SWF: such tests did this)', short: 'Satellite damaged' },
        },
      },
    ],
    phoneHide: ['Thor launch'],
    still: 0.7,
    camDist: 3.5,
    phoneK: 1.5, // 375: zoomed out so the whole belt (L up to 1.7, field-line arches included) and the globe fit
    staticZoom: 1.7,
    staticCenter: [35, -205],
    stillCam: { at: [16, -160, 4.2], look: [0, 0, 0], hideShell: true },
    status: [
      [0, 'Thor rocket climbs toward ~400 km'],
      [0.16, 'Detonation: electrons trapped on Earth’s field lines', 'Detonation: electrons trapped'],
      [0.3, 'Trapped electrons spread in longitude and latitude along field lines', 'Electrons spread along field lines'],
      [0.75, 'Belt has drifted around Earth (illustrative spread)', 'Belt drifts around Earth (illustrative)'],
      [0.82, 'SWF: effects of such tests damaged or destroyed satellites in orbit at the time', 'Satellites in orbit were damaged (SWF)'],
    ],
  },
  {
    id: 'solwind',
    fitPct: 0.99,
    date: '1985-09-13',
    title: 'ASM-135 vs. Solwind (1985)',
    shells: ['LEO'],
    duration: 12,
    caption:
      'An F-15 in a supersonic zoom climb releases an ASM-135 missile. The missile’s miniature homing vehicle rises to meet' +
      ' the Solwind P78-1 satellite' +
      ' at about 530 km (SWF Table 5-1; its text says 555 km) and destroys it by collision. SWF counts 285 tracked fragments; all have since decayed. The' +
      ' positions and the debris spread are drawn for legibility, not computed.',
    cite: 'SWF 2026, Table 5-1: 285 tracked, 0 still in orbit (p. 05-01); Table 1-4, p. 01-24; ASM-135 and the zoom climb, Figure 1-8 text.',
    related: null,
    event: 'us-1985-solwind',
    launchPhoneK: 1.2,
    launchAt: [3.3, 0.95, 0.8],
    hit: { lat: 37.5, lon: -135.0, alt: 530, inc: 97.6, t: 0.5, wa: 0.15, wf: 0.5 },
    actors: [
      {
        type: 'aircraft',
        path: [
          [32.5, -114.0],
          [35.0, -124.0],
        ],
        alt: 12,
        t0: 0.0,
        t1: 0.24,
        label: 'F-15 zoom climb',
        dx: -64,
        dy: 24,
      },
      {
        type: 'target',
        label: 'Solwind P78-1',
        color: C.tgt,
        big: 1.5,
        bright: true,
        impactLabel: 'Impact: Solwind P78-1',
        impactShort: 'Impact',
      },
      { type: 'intercept', from: 'aircraft', t0: 0.24, color: C.int, label: 'ASM-135', flash: 0.42 },
      { type: 'debris', count: 285, spreadAlt: 150, spreadInc: 2.6, spreadRaan: 1.8, dv: 0.6, decay: 0.9, color: '#ffd2a6' },
    ],
    still: 0.56,
    status: [
      [0, 'F-15 in a supersonic zoom climb'],
      [0.24, 'Missile released; homing vehicle rises to the satellite', 'Missile released; vehicle rises to satellite'],
      [0.52, 'Collision at ~530 km; fragments spread and decay', 'Collision at ~530 km'],
      [0.75, 'Time compressed: SWF counts 285 tracked fragments, all since decayed', 'SWF: 285 fragments, all decayed'],
    ],
  },
  {
    id: 'fengyun',
    fitPct: 0.94,
    date: '2007-01-11',
    title: 'Fengyun-1C (2007)',
    shells: ['LEO'],
    duration: 16,
    caption:
      'China’s SC-19 interceptor strikes the Fengyun-1C weather satellite at about 880 km (SWF Table 5-1). At that altitude, fragments stay up for' +
      ' decades. They spread along the old orbit into a ring around the planet. It produced the most cataloged fragments of any test in SWF’s Table 5-1.',
    cite: 'SWF 2026, Table 5-1, p. 05-01 (3,532 cataloged; 2,351 in orbit as of Feb. 2026).',
    related: 'unga-77-41',
    event: 'cn-2007-fy1c',
    hit: { lat: 35.5, lon: 106.5, alt: 880, inc: 98.6, t: 0.3, wa: 0.4 },
    launchCam: 'second',
    orbitAt: [26, 74, 4.6],
    phoneK: 1.14,
    noSimCount: true,
    actors: [
      { type: 'site', at: [28.2, 102.0], label: 'Xichang', color: C.ground },
      { type: 'target', label: 'Fengyun-1C', color: C.tgt, big: true, impactDx: 100, impactDy: -100 },
      { type: 'intercept', from: [28.2, 102.0], t0: 0.14, color: C.int, label: 'SC-19' },
      {
        type: 'debris',
        count: 3532,
        spreadAlt: 260,
        spreadInc: 1.6,
        dv: 0.9,
        decay: 0,
        color: C.debris,
        label: 'Debris ring',
        dx: 70,
        dy: -50,
        late: { t0: 0.6, k: 1.4, kr: 6 },
      },
    ],
    still: 0.85,
    status: [
      [0, 'SC-19 rises toward Fengyun-1C'],
      [0.32, 'Collision at ~880 km: debris spreads along the old orbit', 'Collision at ~880 km'],
      [0.6, 'Ring forms · SWF: 2,351 of 3,532 cataloged pieces still in orbit (Feb. 2026)', 'SWF: 2,351 of 3,532 still in orbit'],
      [0.76, 'Time compressed: the ring spreads into a wider, thinner band · SWF: 2,351 of 3,532 still in orbit', 'Time compressed: band spreads wider'],
    ],
  },
  {
    id: 'burnt-frost',
    date: '2008-02-20',
    title: 'Burnt Frost: SM-3 vs. USA-193 (2008)',
    shells: ['LEO'],
    duration: 12,
    caption:
      'A US Navy cruiser fires a modified SM-3 at the failing USA-193 satellite at about 220 km (SWF’s text says 240 km; its Table 5-1 says 220 km).' +
      ' At that altitude the 175 trackable pieces took about 20 months to de-orbit; the animation compresses that ' +
      'time. The event shows the overlap between' +
      ' missile defense and anti-satellite capability.',
    cite: 'SWF 2026, Table 5-1, p. 05-01 (175 cataloged; 0 in orbit); decay time and 240 km in text, p. 01-24.',
    related: null,
    event: 'us-2008-burnt-frost',
    phoneK: 1.15,
    launchAt: [3.3, 0.95, 0.8],
    earlyKey: true,
    hit: { lat: 29.0, lon: -173.0, alt: 220, inc: 58.5, t: 0.42, wa: 0.15, wf: 0.5 },
    actors: [
      { type: 'ship', at: [22.0, -163.0], label: 'USS Lake Erie', dx: 0, dy: 70 },
      {
        type: 'target',
        label: 'USA-193',
        color: C.tgt,
        big: 1.7,
        minPx: 46,
        maxPx: 86,
        bright: true,
        fall: [
          { k: 1.5, di: 0.2, dr: 0.01, dw: 0.9 },
          { k: 1.25, di: -0.3, dr: -0.012, dw: 1.05 },
          { k: 1.05, di: 0.4, dr: 0.02, dw: 1.15 },
        ],
      },
      { type: 'intercept', from: [22.0, -163.0], t0: 0.2, color: C.int, label: 'SM-3', flash: 0.42, strong: true },
      { type: 'debris', count: 175, spreadAlt: 90, spreadInc: 2.6, spreadRaan: 1.6, dv: 0.6, decay: 2.2, color: '#ffd2a6', size: 0.046, lateGlow: true },
    ],
    still: 0.47,
    status: [
      [0, 'Interceptor rises toward the satellite'],
      [0.44, 'Collision at ~220 km; low-altitude fragments decay quickly', 'Collision at ~220 km'],
      [0.6, 'Time compressed: SWF reports ~20 months to de-orbit entirely', 'SWF: ~20 months to de-orbit'],
    ],
  },
  {
    id: 'dn2',
    date: '2013-05-13',
    title: 'DN-2 “high-altitude science” launch (2013)',
    shells: ['LEO', 'MEO', 'GEO'],
    duration: 14,
    caption:
      'A rocket from Xichang climbs on a suborbital path toward the geostationary belt and falls back to Earth. China said it reached 10,000 km.' +
      ' The US military said it went “nearly to GEO”, and US officials said the upper stages re-entered “over the Indian Ocean”.' +
      ' SWF cites an analysis' +
      ' putting the apogee at 30,000 km or more. There was no target. The launch showed reach, not an intercept.',
    cite: 'SWF 2026, pp. 03-20, 03-22.',
    related: null,
    event: 'cn-2013-dn2',
    actors: [
      { type: 'site', at: [28.2, 102.0], label: 'Xichang', color: C.ground, offGlobe: true },
      {
        type: 'suborbital',
        from: [28.2, 102.0],
        to: [-20.0, 78.0],
        apex: 30000,
        t0: 0.05,
        t1: 0.9,
        color: '#ff7a7a',
        thick: 0.011,
        label: 'DN-2 path (no target: not an intercept)',
        short: 'DN-2 path · no target',
        labelIdx: 0.17,
        dx: -40,
        dy: -50,
        head: true,
        apexT: 0.47,
        staticAt: [0.6, 0.09],
        marks: [
          { alt: 10000, label: '10,000 km · China’s stated figure', short: '10,000 km', opt: true, color: '#ffd9a0', dx: -20, dy: -40 },
          { alt: 30000, label: 'Apogee ≥30,000 km (SWF-cited)', short: '≥30,000 km (SWF)', opt: true, color: '#ff9c9c', apex: true, dx: 0, dy: -68 },
          { alt: GEO_ALT, label: 'GEO ring · 35,786 km', short: 'GEO', opt: true, color: C.geo, dx: 0, dy: 46 },
        ],
      },
      { type: 'ring', alt: GEO_ALT, inc: 0, raan: 0, color: C.geo, thick: 0.006, opacity: 0.9, sats: 10 },
    ],
    still: 0.62,
    camDist: 7.5,
    stillCam: { at: [22, 8, 7.9], look: [0, 90, 0.7] },
    status: [
      [0, 'Rocket climbs from Xichang on a suborbital path'],
      [0.4, 'Analysis cited by SWF: apogee ≥30,000 km, toward GEO (35,786 km)', 'SWF-cited analysis: apogee ≥30,000 km'],
      [0.8, 'US officials: upper stages re-entered “over the Indian Ocean” · no target, not an intercept', 'Re-entry over Indian Ocean (US officials)'],
    ],
    shellLabels: { MEO: null, GEO: null },
    noRing: ['GEO'],
    staticFit: 1.9,
    cameras: [
      { name: 'Follow the rocket', short: 'Follow', trackPath: { tilt: 45, lift: 0.55, ring: true, geoT: 0.1, fill: 0.92 } },
      { name: 'Profile', at: [22, 8, 7.6], look: [0, 90, 0.7], phone: { at: [24, 24, 8.6], look: [0, 96, 0.7] } },
      { name: 'Polar', at: [78, 80, 8.4], phone: { at: [78, 80, 7.2] }, hide: ['DN-2 path', '10,000'] },
      { name: 'Zoom', at: [20, 45, 5.6], phone: { hide: ['DN-2 path'] } }, // 375: the path label would sit on the disc, crowding Xichang and 10,000 km
    ],
  },
  {
    id: 'shakti',
    date: '2019-03-27',
    title: 'Mission Shakti (2019)',
    shells: ['LEO'],
    duration: 12,
    caption:
      'India’s PDV Mk-II interceptor destroys the Microsat-R satellite at about 300 km. Indian officials said the debris would re-enter within 45' +
      ' days. SWF counts 130 cataloged fragments, none still in orbit.',
    cite: 'SWF 2026, Table 5-1, p. 05-01; p. 04-04.',
    related: 'unga-77-41',
    event: 'in-2019-shakti',
    launchAt: [2.67, 1.55, 0.5],
    earlyKey: true,
    camHide: { 3: ['Abdul Kalam', 'PDV', 'LEO'] }, // Polar: the strike is a few px wide there, so its neighbours' labels are dropped
    hit: { lat: 26.0, lon: 95.0, alt: 300, inc: 96.6, t: 0.38, wa: 0.15, wf: 0.5 },
    actors: [
      { type: 'site', at: [20.75, 87.08], label: 'Abdul Kalam Island', color: C.ground },
      {
        type: 'target',
        label: 'Microsat-R',
        color: C.tgt,
        big: 1.7,
        minPx: 46,
        maxPx: 86,
        bright: true,
        wreck: true,
        impactDx: -80,
        impactDy: -30,
        impactLabel: 'Impact: Microsat-R (wreck)',
        impactShort: 'Impact',
      },
      { type: 'intercept', from: [20.75, 87.08], t0: 0.16, color: C.int, label: 'PDV Mk-II', flash: 0.32 },
      {
        type: 'debris',
        count: 130,
        spreadAlt: 170,
        spreadInc: 3.6,
        spreadRaan: 2.6,
        dv: 1.2,
        drift: 0.15,
        decay: 1.5,
        color: '#ffd2a6',
        size: 0.075,
        lateGlow: true,
      },
    ],
    still: 0.43,
    status: [
      [0, 'PDV Mk-II rises from Abdul Kalam Island'],
      [0.4, 'Collision at ~300 km; fragments spread and decay quickly', 'Collision at ~300 km'],
      [0.65, 'Time compressed: SWF counts 130 cataloged pieces, none still in orbit', 'SWF: 130 pieces, none in orbit'],
    ],
  },
  {
    id: 'cosmos1408',
    fitPct: 0.92,
    date: '2021-11-15',
    title: 'Nudol vs. Cosmos 1408 (2021)',
    shells: ['LEO'],
    duration: 16,
    caption:
      'Russia’s Nudol interceptor destroys the defunct Cosmos 1408 at about 470 km. The debris cloud spreads across altitudes' +
      ' that cross the International' +
      ' Space Station’s orbit (drawn schematically), and the ISS crew sheltered in their docked spacecraft. SWF counts 1,807 cataloged fragments, 5 still' +
      ' in orbit as of February 2026.',
    cite: 'SWF 2026, Table 5-1, p. 05-01; Table 2-4, p. 02-21.',
    related: 'us-moratorium-2022',
    event: 'ru-2021-cosmos1408',
    hit: { lat: 66.0, lon: 52.0, alt: 470, inc: 82.6, t: 0.3, wa: 0.4, wf: 0.6 },
    camHide: { 2: ['Impact'], 3: ['Plesetsk', 'Impact'] },
    launchCam: 'second',
    orbitAt: [52, 28, 4.5],
    phoneK: 1.16,
    noSimCount: true,
    actors: [
      { type: 'site', at: [62.9, 40.6], label: 'Plesetsk', color: C.ground, dx: -110, dy: -16 },
      {
        type: 'ring',
        alt: 420,
        inc: 51.6,
        color: C.iss,
        crossHit: 0.55,
        thick: 0.0032,
        opacity: 0.85,
        sat: { speed: 0.16, label: 'ISS (illustrative orbit)', short: 'ISS (illustrative)', iss: true, big: 1.3, minPx: 44, maxPx: 90, dx: 96, dy: 14 },
      },
      { type: 'target', label: 'Cosmos 1408', color: C.tgt, big: true, impactDx: -40, impactDy: 64, dx: -40, dy: 62 },
      { type: 'intercept', from: [62.9, 40.6], t0: 0.17, color: C.int, label: 'Nudol' },
      {
        type: 'debris',
        count: 1807,
        spreadAlt: 150,
        spreadInc: 5,
        spreadRaan: 2.2,
        dv: 1.0,
        decay: 0.25,
        color: C.debris,
        label: 'Debris of Cosmos 1408',
        short: 'Cosmos 1408 debris',
        dx: 60,
        dy: -34,
      },
    ],
    still: 0.8,
    status: [
      [0, 'Nudol rises toward Cosmos 1408; the ISS orbit is drawn below it (illustrative)', 'Nudol rises toward Cosmos 1408'],
      [0.32, 'Collision at ~470 km: debris cloud spreads across the ISS orbit', 'Collision at ~470 km; debris spreads'],
      [0.6, 'Cloud crosses the ISS orbit · SWF: 5 of 1,807 pieces still in orbit (Feb. 2026)', 'SWF: 5 of 1,807 pieces still in orbit'],
    ],
  },
  {
    id: 'gnss',
    date: '2023-12-01',
    title: 'GNSS jamming over the Baltic',
    shells: ['LEO', 'MEO'],
    shellLabels: { MEO: null },
    staticShellLabels: { MEO: 'GPS orbit · MEO' },
    duration: 16,
    caption:
      'GPS satellites orbit in medium Earth orbit (MEO), far above the aircraft. A jammer on the ground swamps their weak signals only inside its' +
      ' local effect zone. Aircraft crossing the zone lose their position fix, while aircraft outside it and the satellites themselves are unaffected.' +
      ' This is interference with receivers, not an attack on a satellite.',
    cite: 'SWF 2026, pp. 02-29 to 02-30; p. 12-05 (downlink jamming has no effect on the satellites).',
    related: 'icao-2025',
    event: 'ru-2023-baltic',
    actors: [
      {
        type: 'constellation',
        alt: 20200,
        inc: 55,
        planes: 6,
        per: 3,
        color: C.gps,
        speed: 0.25,
        inset: true,
        label: 'GPS satellites · MEO',
        opt: true,
        dx: -50,
        dy: 40,
      },
      {
        type: 'zone',
        at: [57.5, 21.0],
        radius: 6.2,
        color: C.jam,
        label: 'Jammer effect zone',
        dx: 40,
        dy: -34,
        jammer: { at: [56.5, 21.0], label: 'Ground jammer (illustrative)', short: 'Jammer', dx: -70, dy: 30 },
      },
      {
        type: 'aircraft',
        path: [
          [53.0, 8.0],
          [61.0, 32.0],
        ],
        alt: 11,
        t0: 0,
        t1: 1,
        label: 'Airliner A',
        gnss: true,
        dx: -96,
        dy: -14,
      },
      {
        type: 'aircraft',
        path: [
          [43.0, 2.0],
          [44.0, 30.0],
        ],
        alt: 11,
        t0: 0,
        t1: 1,
        label: 'Airliner B',
        beamLabel: 'GPS signal (from a MEO satellite, off view)',
        beamShort: 'GPS signal',
        beamDx: 50,
        beamDy: 22,
        gnss: true,
        labelDy: 34,
        dx: 92,
      },
    ],
    still: 0.45,
    camDist: 3.5,
    phoneK: 0.82,
    stillCam: { at: [49, 14, 1.85], look: [51.5, 16, 0.98], hideShell: true },
    focus: [55, 18],
    inset: 'GPS orbits (top view)',
    insetCorner: 'bl',
    insetSize: [150, 116],
    insetNoPhone: true, // the phone stage is too small for an inset that would sit on the jammer zone
    cameras: [
      {
        name: 'Baltic: airliners and jammer zone',
        short: 'Baltic zone',
        at: [41, 13, 1.5],
        look: [53.4, 22.6, 0.98],
        phone: { at: [38, 12, 1.48] },
      },
      { name: 'Close-up: jammer and airliners', short: 'Close-up', at: [47, 16, 1.7], look: [54, 19, 0.98], phone: { at: [47, 16, 1.95] } },
      { name: 'Europe + GPS orbits', short: 'Europe + GPS', at: [42, -8, 5.0], look: [40, 10, 0.5], ref: false, hide: ['Ground jammer', 'Jammer effect'] },
    ],
    status: [
      [0, 'Both airliners have GNSS (green) ·' + ' jammer zone in red · satellites unaffected', 'Airliners have GNSS (green) · zone in red'],
      [0.3, 'Inside the zone GNSS is lost (red); outside it' + ' stays OK (green). Satellites unaffected', 'Inside the zone GNSS is lost (red)'],
    ],
  },
  {
    id: 'viasat',
    inset: 'Context: KA-SAT in GEO (top view)',
    date: '2022-02-24',
    title: 'Viasat KA-SAT cyberattack (2022)',
    shells: ['GEO'],
    duration: 14,
    caption:
      'Within hours of Russian troops crossing into Ukraine in February 2022, attackers pushed destructive ' +
      '“AcidRain” malware through KA-SAT’s ground' +
      ' management network. Tens of thousands of user modems in Ukraine and across Europe went dark. The satellite itself kept working: the attack hit' +
      ' the ground segment.',
    cite: 'SWF 2026, pp. 15-06 to 15-07 (attributed to Russia by the US, UK and EU, May 2022).',
    related: 'tallinn-2017',
    event: 'ru-2022-viasat',
    actors: [
      { type: 'ring', alt: GEO_ALT, inc: 0, raan: 0, color: C.geo, thick: 0.003, opacity: 0.5, inset: true },
      {
        type: 'geo',
        lon: 9,
        insetLabel: 'KA-SAT',
        minPx: 26,
        maxPx: 64,
        label: 'KA-SAT (GEO, unaffected)',
        short: 'KA-SAT (GEO)',
        dx: 0,
        dy: -50,
        color: C.geo,
        dimT0: 0.4,
        dimT1: 0.7,
        hub: [46, 8],
        hubLabel: 'Ground management network (illustrative)',
        hubShort: 'Ground network',
        hubDx: -60,
        hubDy: 40,
        pulse: [0.1, 0.3],
        beams: [
          [50, 30],
          [48, 10],
          [52, 0],
          [46, 20],
          [55, 15],
        ],
      },
      {
        type: 'terminals',
        boxes: [
          [44, 52, 22, 40, 0.34, 0],
          [47, 55, 6, 22, 0.28, 1],
          [43, 50, -6, 8, 0.2, 2],
          [54, 60, 6, 26, 0.18, 3],
        ],
        count: 900,
        pulse0: 0.1,
        t0: 0.3,
        t1: 0.62,
        labelOffDisc: true, // stills: the label sits beside the globe, not on it
        label: 'Ground terminals (modems)',
        short: 'Terminals',
        labelDx: 120,
        labelDy: -84,
      },
      // One shock ring per region, in the order the modems go dark (illustrative regions; SWF gives no region order).
      { type: 'flash', at: [48, 31, 0], t0: 0.3, color: '#ffb3b3', ringColor: '#ff6b6b', size: 0.2, span: 0.14 },
      { type: 'flash', at: [51, 14, 0], t0: 0.38, color: '#ffb3b3', ringColor: '#ff6b6b', size: 0.2, span: 0.14 },
      { type: 'flash', at: [46, 1, 0], t0: 0.46, color: '#ffb3b3', ringColor: '#ff6b6b', size: 0.2, span: 0.14 },
      { type: 'flash', at: [57, 16, 0], t0: 0.54, color: '#ffb3b3', ringColor: '#ff6b6b', size: 0.2, span: 0.14 },
    ],
    steps: [
      [0, 'Network normal: KA-SAT serves user modems across Ukraine and Europe'],
      [0.1, 'Attackers push AcidRain wiper malware through the ground' + ' management network'],
      [0.3, 'Commands reach user modems region by region; modems are wiped and go offline'],
      [0.62, 'Tens of thousands of modems offline; the satellite itself keeps operating'],
      [0.8, 'Attributed to Russia (GRU) by the US, UK and EU in May 2022 (SWF' + ' 15-07)'],
    ],
    still: 0.75,
    camDist: 5.6,
    focus: [33, 12],
    shellLabels: { GEO: null },
    staticZoom: 1.5,
    stillCam: { at: [10, 12, 3.9], look: [24, 13, 0.5], hideShell: true },
    cameras: [
      { name: 'Europe (zoom)', short: 'Europe', at: [32, 14, 2.15], look: [50, 19, 1.0], phone: { at: [32, 14, 2.2], look: [56, 20, 1.0] }, insetRef: true },
      { name: 'Europe + KA-SAT', short: 'Wide Europe', at: [10, 12, 3.9], look: [24, 13, 0.5], phone: { at: [10, 12, 4.5] } },
      { name: 'Ground network', short: 'Network', at: [42, -2, 2.3], look: [46, 14, 1.0], ref: false },
      { name: 'Wide', at: [30, -6, 6.5], hide: ['Ground management'] }, // its label would need a leader across the whole globe
    ],
  },
  {
    id: 'laser',
    date: '1997-10-17',
    title: 'MIRACL laser test on MSTI-3 (1997)',
    shells: ['LEO'],
    duration: 12,
    caption:
      'In October 1997 the US fired the MIRACL chemical laser at MSTI-3, a retired Air Force experimental satellite with infrared sensors. MIRACL' +
      ' is now part of a facility at White Sands Missile Range, New Mexico, where this diagram places it. A low-power ' +
      'beam can dazzle a sensor; a high-power' +
      ' beam could damage it. SWF describes Russia’s Peresvet as a mobile laser dazzler (Russia view: shelter sites only).',
    cite: 'SWF 2026, p. 01-35 (MIRACL); pp. 02-35 to 02-36 (Peresvet shelter sites; site markers approximate).',
    related: null,
    event: 'us-1997-miracl',
    hit: { lat: 32.4, lon: -106.4, alt: 420, inc: 97.0, t: 0.5, wa: 0.3, wf: 0.22 },
    lift: 30,
    stillShort: ['MIRACL beam'],
    staticT: 0.16, // static: the satellite well along its pass, so the beam is drawn at full length
    staticZoom: 2.6,
    staticCenter: [35, -108],
    actors: [
      { type: 'site', at: [32.4, -106.4], label: 'White Sands Missile Range, NM', short: 'White Sands', color: C.ground, dx: -96, dy: 30 },
      { type: 'target', label: 'MSTI-3 (US test target)', short: 'MSTI-3', color: C.tgt, noHit: true, big: 1.7, minPx: 46, maxPx: 84, dx: 92, dy: -26 },
      {
        type: 'beam',
        from: [32.4, -106.4],
        window: 0.42,
        color: C.laser,
        label: 'MIRACL beam (illustrative)',
        short: 'MIRACL beam',
        width: 0.034,
        dx: 96,
        dy: -20,
        labelOffDisc: true,
      },
      { type: 'site', at: [56.86, 40.53], label: 'Peresvet shelters: Teykovo', short: 'Teykovo', color: '#ffb0f0', dx: 0, dy: 30, small: true, liveOnly: true },
      { type: 'site', at: [56.63, 47.89], label: 'Yoshkar-Ola', color: '#ffb0f0', dx: 40, dy: -18, small: true, liveOnly: true },
      { type: 'site', at: [55.03, 82.92], label: 'Novosibirsk', color: '#ffb0f0', dx: 0, dy: 26, small: true, liveOnly: true },
    ],
    still: 0.5,
    status: [
      [0, 'MSTI-3 rises over White Sands'],
      [0.15, 'MIRACL beam tracks the satellite while it is above the horizon', 'MIRACL beam tracks the satellite'],
      [0.8, 'Same principle: SWF describes Russia’s Peresvet (named in 2018) as a mobile laser dazzler', 'SWF: Russia’s Peresvet is a laser dazzler'],
    ],
    cameras: [
      { name: 'Follow the satellite', fit: { site: [32.4, -106.4], tilt: 55 } },
      { name: 'Side view', fit: { site: [32.4, -106.4], tilt: 58, side: -1, fill: 0.72 } },
      {
        name: 'Zoom on MSTI-3',
        fit: { site: [32.4, -106.4], tilt: 10, fill: 0.8, dMax: 4.6 },
        phone: { fit: { site: [32.4, -106.4], tilt: 10, fill: 0.7, dMax: 4.6 } },
      },
      {
        name: 'Russia: Peresvet sites (SWF)',
        at: [50, 55, 2.3],
        look: [56, 58, 1.0],
        ref: false,
        hide: ['MSTI-3', 'MIRACL', 'White Sands'],
        status: ['SWF: Russia’s Peresvet is a mobile laser dazzler; pins mark its shelter sites', 'Peresvet shelter sites (approx.)'],
      },
    ],
  },
  // ---------------------------------------------------------------- co-orbital scenes (SWF 2026): sj21-tug, rpo, spaceplanes
  {
    id: 'sj21-tug',
    date: '2022-01-21',
    title: 'SJ-21 pulls a defunct satellite out of the GEO belt (2022)',
    shells: [],
    duration: 24,
    caption:
      'SWF reports that China’s SJ-21 rendezvoused with Compass G2, a defunct Chinese navigation satellite, in December 2021, “docked to it at some' +
      ' point”, and around 21 January 2022 used its own propulsion to pull both objects above the GEO belt (by 27 January: 290' +
      ' to 3,100 km above the protected' +
      ' zone). SJ-21 then came back down close to GEO. SWF does not say how SJ-21 captured or docked with Compass ' +
      'G2, so the scene shows a docking contact,' +
      ' not an arm. SWF does report robotic-arm demonstrations on other Chinese satellites: SY-7 (2013, p. 03-02) and Aolong-1 (2016, p. 03-04).',
    cite:
      'SWF 2026, p. 03-11 (SJ-21 and Compass G2) and Table 3-2, p. 03-15; robotic arms on other satellites: SY-7 p. 03-02, Aolong-1 p. 03-04, SJ-17' +
      ' p. 03-08.',
    related: null,
    event: 'cn-2022-sj21-compass-g2',
    inset: 'Context: top view',
    insetNoPhone: true, // on a phone the inset would cover the docked pair
    scaleNote: 'Heights above the belt, the spacing between the two spacecraft and their position along the belt are illustrative.',
    anchors: { g: { geo: { lon: 105 } } },
    actors: [
      { type: 'ring', alt: GEO_ALT, inc: 0, raan: 0, color: C.geo, thick: 0.005, opacity: 0.85, inset: true, label: 'GEO belt (35,786 km)' },
      {
        type: 'craft',
        id: 'cg2',
        variant: 'navsat',
        anchor: 'g',
        color: C.dead,
        scale: 2.2 * PK,
        minPx: 80,
        maxPx: 112,
        label: 'Compass G2 (defunct)',
        short: 'Compass G2',
        staticKey: [[0, 0.1, 0.72, 0], [1, 0.1, 0.72, 0]], // static: well above the belt line
        dx: 60,
        dy: 34,
        labelFn: (t) => (t >= 0.4 && t < 0.8 ? null : 'Compass G2 (defunct)'),
        arcs: [{ t0: 0.5, t1: 0.76, o: [0.09, 0, 0] }],
        key: [
          [0, 0, 0, 0],
          [0.4, 0.03, 0, 0],
          [0.5, 0.03, 0, 0],
          [0.76, 0.11, 0.27, 0],
          [1, 0.135, 0.275, 0.004],
        ],
      },
      {
        type: 'craft',
        id: 'sj21',
        variant: 'tug',
        anchor: 'g',
        color: C.cn,
        bright: true,
        scale: 2.2 * PK,
        minPx: 80,
        maxPx: 112,
        label: 'SJ-21 (China)',
        short: 'SJ-21',
        staticKey: [[0, 0.1, 0.72, 0], [1, 0.1, 0.72, 0]], // static: well above the belt line
        dx: -68,
        dy: -12,
        labelFn: (t, n) => (t >= 0.4 && t < 0.8 ? (n ? 'SJ-21 + G2 docked' : 'SJ-21 + Compass G2 (docked)') : 'SJ-21' + ' (China)'),
        arcs: [{ t0: 0.8, t1: 0.97, o: [0.07, 0.06, 0] }],
        dock: { with: 'cg2', t0: 0.4, t1: 0.8 },
        key: [
          [0, 0.72, 0, 0],
          [0.2, 0.3, 0, 0],
          [0.27, 0.17, 0.006, -0.008],
          [0.34, 0.09, -0.004, 0.006],
          [0.4, 0.03, 0, 0],
          [0.8, 0.112, 0.2705, 0.0003],
          [0.86, 0.16, 0.28, 0.012],
          [0.97, 0.08, 0.0, 0.0],
          [1, 0.07, 0, 0],
        ],
      },
      { type: 'burst', craft: 'sj21', t0: 0.4, color: '#fff1c1', ringColor: C.cn, size: 0.12, span: 0.07 },
      { type: 'trail', craft: 'sj21', t0: 0.47, t1: 0.97, color: C.cn },
      { type: 'trail', craft: 'cg2', t0: 0.5, t1: 0.8, color: C.dead },
    ],
    still: 0.78,
    staticT: 0.74, // static: the pair drawn clearly above the belt (not straddling the ring)
    status: [
      [0, 'SJ-21 (China) approaches Compass G2, a defunct Chinese navigation satellite (25 Dec. 2021)', 'SJ-21 approaches defunct Compass G2'],
      [0.2, 'For several weeks SJ-21 keeps in tight proximity to Compass G2', 'SJ-21 stays close to G2 for weeks'],
      [0.34, 'SWF: SJ-21 “docked to it at some point” (how is not described)', 'SWF: SJ-21 “docked to it at some point”'],
      [0.5, 'Around 21 Jan. 2022 SJ-21’s own propulsion pulls both objects above the GEO belt', 'About 21 Jan.: SJ-21 pulls both above GEO'],
      [0.72, 'By 27 Jan. both are in an orbit 290–3,100 km above the protected GEO zone (height exaggerated)', 'By 27 Jan.: 290–3,100 km above GEO zone'],
      [0.8, 'SWF does not describe the separation; it says SJ-21 later lowered its orbit back close to GEO', 'SJ-21 later lowered its orbit near GEO'],
      [0.96, 'SJ-21 is near GEO again; SWF’s table says Compass G2 was pulled “well past graveyard orbit”', 'G2 pulled “well past graveyard orbit”'],
    ],
    cameras: [
      { name: 'Follow the pair (tight + context inset)', ...ARM_TAG, fitCraft: { anchor: 'g', ids: ['sj21', 'cg2'], dir: [-0.3, 0.8, 0.55], fill: 0.93 } },
      { name: 'Whole event (Earth + GEO belt)', short: 'Whole event', at: [36, 104, 3.9], look: [0, 106, 1.9], phone: { at: [36, 104, 4.8] } },
      { name: 'Approach and docking', ...ARM_TAG, fitCraft: { anchor: 'g', ids: ['sj21', 'cg2'], dir: [-0.9, 0.3, 0.55], fill: 0.7, dMin: 0.5, t: 0.3 } },
      { name: 'Pull (angled)', fitCraft: { anchor: 'g', ids: ['sj21', 'cg2'], dir: [-0.7, 0.55, 0.45], fill: 0.7, dMin: 0.5, t: 0.6 } },
      { name: 'GEO belt (wide)', at: [26, 70, 7.4] },
    ],
    stillCam: { at: [24, 12, 4.7], look: [0, 105, 1.25], hideShell: true },
    staticCenter: [25, 72],
    staticCraftMax: 54,
    staticCraftMaxPhone: 44,
    staticFit: 1.9,
    staticFitPhone: 1.7,
  },
  {
    id: 'rpo',
    date: '2025-06-13',
    title: 'Proximity operations: China, the US and Russia (2019–2025)',
    shells: [],
    duration: 32,
    caption:
      'Three separate episodes from SWF’s RPO tables. (1) GEO, 2025: China’s SJ-21 and SJ-25 approach, appear to dock and later separate, while two' +
      ' US GSSAP satellites are positioned “flanking” them. (2) LEO, 2019–20: Russia’s Cosmos 2542 releases Cosmos 2543, which' +
      ' then works near a US satellite,' +
      ' USA 245. (3) GEO, 2025: a US GSSAP satellite and the UK’s SKYNET 5A in a jointly announced RPO. SWF hedges the intent behind the first two; an' +
      ' RPO is not an attack.',
    cite:
      'SWF 2026: Tables 1-3 (p. 01-15), 2-3 (p. 02-15), 3-2 (p. 03-16); SJ-21 and SJ-25 pp. 03-12 to 03-13; Cosmos 2542 pp. 02-09 to 02-10; USA 271' +
      ' and SKYNET 5A p. 01-14.',
    related: null,
    event: 'cn-2025-sj21-sj25-docking',
    panels: [
      {
        t: 0.3,
        title: '1 · GEO, 2025',
        brief: 'SJ-21 + SJ-25 dock, GSSAP flank',
        short: 'SJ-21 + SJ-25',
        status: 'SJ-21 and SJ-25 appear to dock; two' + ' US GSSAP satellites are positioned' + ' “flanking” them',
      },
      { t: 0.6, title: '2 · LEO, 2019–20', brief: 'Cosmos 2543 near USA 245',
        short: 'Cosmos 2543', status: 'Cosmos 2542 releases Cosmos 2543, which works near USA 245' },
      {
        t: 0.85,
        title: '3 · GEO, 2025',
        brief: 'USA 271 near SKYNET 5A',
        short: 'USA 271',
        dropPhone: ['GEO belt'],
        status: 'USA 271 and SKYNET 5A: a jointly announced US–UK RPO',
      },
    ],
    inset: 'Context: top view',
    scaleNote:
      'Distances between spacecraft are exaggerated and orbital motion is slowed so that each episode can be seen; the' +
      ' three episodes are at different' +
      ' times and places.',
    anchors: { g1: { geo: { lon: 127 } }, l1: { orbit: { alt: 600, inc: 97.9, through: [58, 52], tThrough: 0.57, du: 0.4 } }, g3: { geo: { lon: 95.3 } } },
    acts: [
      { t0: 0, t1: 0.42, cam: 1 },
      { t0: 0.42, t1: 0.72, cam: 2 },
      { t0: 0.72, t1: 1, cam: 3 },
    ],
    actors: [
      { type: 'ring', alt: GEO_ALT, inc: 0, raan: 0, color: C.geo, thick: 0.004, opacity: 0.6, inset: true, label: 'GEO belt' },
      { type: 'ring', alt: 600, inc: 97.9, raan: 40, color: '#8fd0ff', thick: 0.0025, opacity: 0.5, inset: true },
      // ---- 1 · China + US in GEO (SJ-21, SJ-25, USA 270, USA 271), June 2025 to January 2026
      {
        type: 'craft',
        id: 'sj25',
        variant: 'tug',
        minPx: 52,
        maxPx: 84,
        anchor: 'g1',
        acts: [0],
        color: C.cn,
        scale: 1.5 * PK,
        label: 'SJ-25 (China)',
        short: 'SJ-25',
        dx: -20,
        dy: 44,
        labelFn: (t) => (t >= 0.27 && t < 0.335 ? null : 'SJ-25 (China)'),
        key: [
          [0, 0, 0, 0],
          [0.335, 0, 0, 0],
          [0.355, -0.1, 0, 0],
          [0.385, -0.06, 0, 0.01],
          [0.398, -0.05, 0, 0],
          [0.415, -0.3, 0, 0],
        ],
      },
      {
        type: 'craft',
        id: 'sj21b',
        variant: 'tug',
        minPx: 52,
        maxPx: 84,
        anchor: 'g1',
        acts: [0],
        color: C.cn,
        bright: true,
        scale: 1.5 * PK,
        label: 'SJ-21 (China)',
        short: 'SJ-21',
        dx: 30,
        dy: -44,
        labelFn: (t, n) => (t >= 0.27 && t < 0.335 ? (n ? 'SJ-21 + SJ-25 docked' : 'SJ-21 + SJ-25' + ' (docked)') : 'SJ-21 (China)'),
        dock: { with: 'sj25', t0: 0.27, t1: 0.335 },
        key: [
          [0, 0.62, 0, 0.01],
          [0.09, 0.26, 0, 0],
          [0.15, 0.2, 0, 0],
          [0.175, 0.1, 0, 0],
          [0.21, 0.24, 0, 0],
          [0.245, 0.1, 0, 0.005],
          [0.27, 0, 0, 0],
          [0.335, 0, 0, 0],
          [0.355, 0.1, 0, 0],
          [0.42, 0.1, 0, 0],
        ],
      },
      {
        type: 'craft',
        id: 'usa270',
        minPx: 52,
        maxPx: 84,
        anchor: 'g1',
        acts: [0],
        color: C.us,
        scale: 1.4 * PK,
        label: 'USA 270 (US GSSAP)',
        short: 'USA 270',
        dx: -10,
        dy: -40,
        key: [
          [0, -1.0, -0.05, 0.02],
          [0.13, -0.5, -0.05, 0.02],
          [0.42, -0.5, -0.05, 0.02],
        ],
      },
      {
        type: 'craft',
        id: 'usa271',
        minPx: 52,
        maxPx: 84,
        anchor: 'g1',
        acts: [0],
        color: C.us,
        scale: 1.4 * PK,
        label: 'USA 271 (US GSSAP)',
        short: 'USA 271',
        dx: 20,
        dy: -34,
        key: [
          [0, 1.0, 0.05, -0.02],
          [0.13, 0.55, 0.05, -0.02],
          [0.42, 0.55, 0.05, -0.02],
        ],
      },
      // ---- 2 · Russia in LEO (Cosmos 2542, Cosmos 2543, USA 245), December 2019 to January 2020
      {
        type: 'craft',
        id: 'c2542',
        minPx: 52,
        maxPx: 84,
        anchor: 'l1',
        acts: [1],
        color: C.ru,
        scale: 1.5 * PK,
        label: 'Cosmos 2542 (Russia)',
        short: 'Cosmos 2542',
        dx: -60,
        dy: 36,
        key: [
          [0.42, 0, 0, 0],
          [0.72, 0, 0, 0],
        ],
      },
      { type: 'burst', craft: 'c2542', t0: 0.447, color: '#ffd9c0', ringColor: C.ru, size: 0.1, span: 0.05 },
      {
        type: 'craft',
        id: 'c2543',
        minPx: 40,
        maxPx: 62,
        anchor: 'l1',
        acts: [1],
        vis: [0.447, 0.72],
        color: C.ru,
        small: true,
        scale: 1.6 * PK,
        label: 'Cosmos 2543',
        short: 'Cosmos 2543',
        dx: 10,
        dy: 40,
        labelFn: (t, n) => (n ? 'Cosmos 2543' : 'Cosmos 2543 (subsatellite)'),
        arcs: [{ t0: 0.53, t1: 0.6, o: [0, 0.07, 0] }],
        key: [
          [0.42, 0, 0, 0],
          [0.447, 0, 0, 0],
          [0.48, 0.08, 0.012, 0.014],
          [0.53, 0.1, 0.014, 0.014],
          [0.6, 0.42, 0.1, 0.02],
          [0.645, 0.53, 0.06, 0.025],
          [0.68, 0.4, 0.09, 0.02],
          [0.72, 0.3, 0.1, 0.02],
        ],
      },
      { type: 'trail', craft: 'c2543', t0: 0.447, t1: 0.68, color: C.ru, acts: [1] },
      {
        type: 'craft',
        id: 'usa245',
        minPx: 52,
        maxPx: 84,
        anchor: 'l1',
        acts: [1],
        color: C.us,
        scale: 1.4 * PK,
        label: 'USA 245 (US satellite)',
        short: 'USA 245',
        dx: 40,
        dy: -40,
        key: [
          [0.42, 0.62, 0.03, 0.05],
          [0.72, 0.6, 0.03, 0.05],
        ],
      },
      // ---- 3 · US + UK in GEO (USA 271, SKYNET 5A), September 2025
      {
        type: 'craft',
        id: 'sky',
        minPx: 52,
        maxPx: 84,
        anchor: 'g3',
        acts: [2],
        color: '#cfd8ea',
        scale: 1.5 * PK,
        label: 'SKYNET 5A (UK)',
        short: 'SKYNET 5A',
        dx: -20,
        dy: 42,
        key: [
          [0.72, 0, 0, 0],
          [1, 0, 0, 0],
        ],
      },
      {
        type: 'craft',
        id: 'usa271b',
        minPx: 52,
        maxPx: 84,
        anchor: 'g3',
        acts: [2],
        color: C.us,
        bright: true,
        scale: 1.5 * PK,
        label: 'USA 271 (US GSSAP)',
        short: 'USA 271',
        dx: 20,
        dy: -40,
        arcs: [{ t0: 0.72, t1: 0.8, o: [0, 0.06, 0] }],
        key: [
          [0.72, 0.95, 0.05, 0],
          [0.8, 0.3, 0.05, 0],
          [0.83, 0.12, 0.05, 0],
          [0.93, 0.12, 0.05, 0],
          [1, -0.4, 0.05, 0],
        ],
      },
      { type: 'burst', craft: 'usa271b', t0: 0.82, color: '#cfe8ff', ringColor: C.us, size: 0.1, span: 0.05 },
      { type: 'trail', craft: 'usa271b', t0: 0.72, t1: 0.83, color: C.us, acts: [2] },
    ],
    still: 0.3,
    staticCenter: [28, 92],
    staticStatus: 'Three separate episodes shown together: 1 China + US in GEO (2025) · 2 Russia in LEO (2019–20)' + ' · 3 US + UK in GEO (2025)',
    status: [
      [0, 'GEO, June 2025: SJ-21 (China) drifts west along the belt toward SJ-25', 'GEO 2025: SJ-21 drifts toward SJ-25'],
      [0.08, 'Two US GSSAP satellites move to positions COMSPOC calls “flanking” SJ-21 and SJ-25', 'US GSSAP satellites “flanking” them'],
      [0.16, '13–14 June: RPOs; on 13 June within 1 km, possibly docked, then separated (COMSPOC)', '13 June: within 1 km, possibly docked'],
      [0.235, '30 June: again close enough to dock; 2–6 July: “thought to have docked”', '30 June–6 July: “thought to have docked”'],
      [0.29, 'SWF: they “remained docked until November 2025”', 'SWF: “remained docked until November 2025”'],
      [0.34, '25 Nov.: SJ-25 burns to separate;' + ' imagery on 29 Nov. shows two satellites', '25 Nov.: SJ-25 burns to separate'],
      [0.385, 'Dec.–Jan.: RPOs continue, closest just under 3 km on' + ' 13 Jan.; 130 km apart by 16 Jan.', 'Jan.: closest just under 3 km (13 Jan.)'],
      [0.42, 'LEO, 6 Dec. 2019: Russia’s Cosmos 2542 releases a small subsatellite, Cosmos 2543', 'LEO 2019: Cosmos 2542 releases 2543'],
      [0.47, 'Cosmos 2543 stays within 2 km of Cosmos 2542 for three days', 'Cosmos 2543 stays within 2 km for three days'],
      [0.53, 'It then raises its apogee (590 km by 16 Dec.)'],
      [0.6, 'Amateur analysis “strongly suggests” the aim was to observe USA 245; within 20 km in Jan.' + ' 2020', 'Analysis: aim was to observe USA 245'],
      [0.665, 'Russia’s Foreign Ministry said Cosmos 2543 posed no threat to USA 245', 'Russia: Cosmos 2543 posed no threat'],
      [0.72, 'GEO, Sept. 2025: USA 271 (US GSSAP) drifts west, about 1.5° per day, toward SKYNET 5A', 'GEO 2025: USA 271 nears SKYNET 5A'],
      [0.8, '4 Sept.: an in-track maneuver; USA 271 stops within 0.05° of SKYNET 5A near 95.3° E', '4 Sept.: USA 271 stops near SKYNET 5A'],
      [0.84, '5–11 Sept.: closest about 13 km. A first joint US–UK RPO, announced by both space commands', '5–11 Sept.: closest about 13 km'],
      [0.94, 'The RPO lasted roughly 5–11 Sept. (SWF)'],
    ],
    cameras: [
      { name: 'Tour (auto)', auto: true, at: [30, 90, 4.9], look: [0, 121, 2.0], phone: { at: [30, 90, 6.0] } },
      { name: 'China + US in GEO', act: 0, fitCraft: { anchor: 'g1', ids: ['sj25', 'sj21b', 'usa270', 'usa271'], dir: [-0.3, 0.8, 0.55], fill: 0.88, t: 0.2 } },
      { name: 'Russia in LEO', act: 1, fitCraft: { anchor: 'l1', ids: ['c2542', 'c2543', 'usa245'], dir: [-0.2, 0.75, 0.6], fill: 0.88, t: 0.57 } },
      { name: 'US + UK in GEO', act: 2, fitCraft: { anchor: 'g3', ids: ['sky', 'usa271b'], dir: [-0.3, 0.8, 0.55], fill: 0.88, t: 0.85 } },
      { name: 'Wide: Earth and GEO belt (episode 1)', at: [30, 90, 4.9], look: [0, 121, 2.0], phone: { at: [30, 90, 6.0] }, ref: false },
    ],
  },
  {
    id: 'spaceplanes',
    date: '2023-12-28',
    title: 'Spaceplanes: the US X-37B and China’s reusable spacecraft (2010–2026)',
    shells: [],
    duration: 32,
    caption:
      'SWF’s flight tables: the US X-37B has flown eight missions since 2010 (six of 224 to 908 days, then OTV-7 in an orbit reaching 38,838 km,' +
      ' then OTV-8, launched in August 2025). China’s reusable experimental spacecraft (CSSHQ) has flown three missions (2 to' +
      ' 276 days) and a fourth launched' +
      ' in February 2026; after flights 2 and 3, objects catalogued as released from it were approached by it repeatedly. SWF' +
      ' says the X-37B has not approached' +
      ' any other object, and mission purposes are not stated. A 2019 PLA analysis, as SWF reports it, warned that the X-37B could become an “aggressive”' +
      ' fighter in space.',
    cite: 'SWF 2026: Table 1-1 (p. 01-08), Figure 1-3 (p. 01-07), pp. 01-04 to 01-09; Table 3-1 (p. 03-08), pp. 03-06 to 03-08.',
    related: null,
    event: 'us-2023-otv7',
    inset: 'Context: top view',
    scaleNote: 'Orbits use the compressed radial scale; the distances to the released objects are exaggerated and orbital motion is slowed.',
    anchors: {
      us: { orbit: { alt: 350, inc: 45, raan: 288, u0: 0.47, du: 3.4 } },
      heo: { ellipse: HEO_ORBIT },
      cn: { orbit: { alt: 600, inc: 50, raan: 250, u0: 1.0, du: 2.0 } },
    },
    acts: [
      { t0: 0, t1: 0.3, cam: 1 },
      { t0: 0.3, t1: 0.54, cam: 2 },
      { t0: 0.54, t1: 1, cam: 3 },
    ],
    actors: [
      // ---- US X-37B, OTV-1 to OTV-6: LEO flights
      { type: 'path', fn: (u) => orbitPos(350, 38, 288, u * 2 * Math.PI), N: 120, color: '#8fd0ff', opacity: 0.8, thick: 0.0034, acts: [0], staticKeep: false },
      {
        type: 'path',
        fn: (u) => orbitPos(350, 54, 288, u * 2 * Math.PI),
        N: 120,
        color: '#8fd0ff',
        opacity: 0.8,
        thick: 0.0034,
        acts: [0],
        label: 'X-37B flights: 300–400 km, 38°–54° (SWF)',
        short: '300–400 km · 38°–54°',
        opt: true,
        staticHide: true,
        staticKeep: false,
        labelIdx: 20,
        dx: 40,
        dy: -30,
      },
      { type: 'path', fn: (u) => orbitPos(350, 45, 288, u * 2 * Math.PI), N: 120, color: C.us, opacity: 1, thick: 0.0055, acts: [0] },
      {
        type: 'craft',
        id: 'x37',
        minPx: 50,
        maxPx: MX,
        anchor: 'us',
        acts: [0],
        model: 'plane',
        color: C.us,
        bright: true,
        scale: 3 * PK,
        label: 'X-37B (US)',
        short: 'X-37B',
        dx: 46,
        dy: -34,
        key: [
          [0, 0, 0, 0],
          [1, 0, 0, 0],
        ],
      },
      { type: 'trail', craft: 'x37', t0: 0.0, t1: 0.3, color: C.us, acts: [0], thick: 0.003 },
      // ---- US X-37B, OTV-7: highly elliptical orbit
      {
        type: 'path',
        fn: (u) => orbitPos(GEO_ALT, 0, 0, u * 2 * Math.PI),
        N: 120,
        color: C.geo,
        opacity: 0.7,
        thick: 0.004,
        acts: [1],
        label: 'GEO ring (35,786 km)',
        short: 'GEO',
        opt: true,
        staticHide: true,
        labelIdx: 92,
        dx: 20,
        dy: 20,
      },
      {
        type: 'path',
        points: ellipsePath(HEO_ORBIT, 360),
        color: C.us,
        opacity: 0.9,
        thick: 0.004,
        acts: [1],
        label: 'OTV-7 orbit: 323 × 38,838 km, 59.1°' + ' (Feb. 2024)',
        short: 'OTV-7 orbit',
        labelIdx: 180,
        dx: 40,
        dy: -20,
      },
      {
        type: 'craft',
        id: 'x37h',
        minPx: 50,
        maxPx: MX,
        anchor: 'heo',
        acts: [1],
        model: 'plane',
        color: C.us,
        bright: true,
        scale: 4.5 * PK,
        label: 'X-37B OTV-7 (US)',
        short: 'OTV-7',
        dx: -60,
        dy: 34,
        key: [
          [0, 0, 0, 0],
          [1, 0, 0, 0],
        ],
      },
      { type: 'trail', craft: 'x37h', t0: 0.24, t1: 0.54, N: 160, color: C.us, acts: [1], thick: 0.003 },
      // ---- China, CSSHQ: flights 2 and 3 and the objects released from them
      {
        type: 'path',
        fn: (u) => orbitPos(600, 50, 250, u * 2 * Math.PI),
        N: 120,
        color: C.cn,
        opacity: 0.55,
        thick: 0.003,
        acts: [2],
        label: 'CSSHQ orbit: about 600 km, 50° (SWF)',
        short: '~600 km · 50°',
        opt: true,
        staticHide: true,
        staticKeep: false,
        labelIdx: 30,
        dx: 30,
        dy: -30,
      },
      {
        type: 'craft',
        id: 'csshq',
        minPx: 44,
        maxPx: IS_PHONE ? 46 : 58,
        anchor: 'cn',
        acts: [2],
        model: 'plane',
        color: C.cn,
        bright: true,
        scale: 1.45 * PK,
        label: 'CSSHQ (China)',
        short: 'CSSHQ',
        dx: -50,
        dy: -34,
        staticAt: [0.1, 0.27],
        labelFn: (t, n) => (t < 0.765 ? (n ? 'CSSHQ flight 2' : 'CSSHQ flight' + ' 2 (China)') : n ? 'CSSHQ flight 3' : 'CSSHQ flight 3 (China)'),
        key: [
          [0.54, 0, 0, 0],
          [1, 0, 0, 0],
        ],
      },
      {
        type: 'craft',
        id: 'objJ',
        minPx: 38,
        maxPx: 60,
        anchor: 'cn',
        acts: [2],
        vis: [0.585, 0.755],
        small: true,
        scale: 1.6 * PK,
        color: C.cn,
        label: 'Object J',
        short: 'Obj. J',
        dx: 40,
        dy: 34,
        staticAt: [0.1, 0.46],
        key: [
          [0.585, 0, 0, 0],
          [0.605, 0.1, 0.01, 0.02],
          [0.625, 0.2, 0.012, 0.03],
          [0.64, 0.062, 0, 0],
          [0.655, 0.2, 0.012, 0.03],
          [0.676, 0.062, 0, 0],
          [0.69, 0.21, 0, 0.03],
          [0.72, 0.075, 0.004, 0.01],
          [0.735, 0.18, 0.01, 0.03],
          [0.755, 0.16, 0.01, 0.03],
        ],
      },
      { type: 'link', a: 'csshq', b: 'objJ', t0: 0.635, t1: 0.647, color: '#fff1c1', width: 0.009 },
      { type: 'link', a: 'csshq', b: 'objJ', t0: 0.671, t1: 0.683, color: '#fff1c1', width: 0.009 },
      {
        type: 'craft',
        id: 'objG',
        minPx: 38,
        maxPx: 60,
        anchor: 'cn',
        acts: [2],
        vis: [0.8, 0.985],
        small: true,
        scale: 1.6 * PK,
        color: C.cn,
        label: 'Object G',
        short: 'Obj. G',
        dx: -46,
        dy: 20,
        staticAt: [0.1, 0.7],
        key: [
          [0.8, 0, 0, 0],
          [0.815, 0.09, 0.01, 0.03],
          [0.86, 0.24, 0.02, 0.04],
          [0.895, 0.08, 0.005, 0.02],
          [0.93, 0.1, 0.005, 0.02],
          [0.96, 0.08, 0.005, 0.02],
        ],
      },
      { type: 'trail', craft: 'csshq', t0: 0.54, t1: 1, color: C.cn, acts: [2], thick: 0.0025 },
      { type: 'trail', craft: 'objJ', t0: 0.585, t1: 0.755, color: '#ffe9a8', acts: [2], thick: 0.0022 },
      { type: 'trail', craft: 'objG', t0: 0.8, t1: 0.985, color: '#ffe9a8', acts: [2], thick: 0.0022 },
    ],
    still: 0.5,
    stillCam: { at: [36, 20, 7.2], look: [0, 0, 0], hideShell: true },
    status: [
      [0, 'X-37B, OTV-1 to OTV-6 (2010–2022): flights of 224, 469, 675, 718, 780 and 908 days (SWF)', 'X-37B OTV-1 to 6: 224 to 908 days'],
      [0.1, 'SWF: the X-37B has flown at 300–400 km and 38°–54° inclination (hobbyist tracking)', '300–400 km, 38°–54° (SWF)'],
      [0.2, 'Runway landings: Vandenberg AFB (OTV-1 to OTV-3) and Kennedy Space Center (OTV-4 to OTV-6)', 'Landings: Vandenberg, then Kennedy'],
      [0.26, 'SWF: to date the X-37B “has not approached nor rendezvoused with any other space objects”', 'SWF: X-37B approached no other object'],
      [0.3, 'OTV-7 (launched 28 Dec. 2023): a highly elliptical orbit, 323 × 38,838 km at 59.1° (Feb. 2024)', 'OTV-7: 323 × 38,838 km at 59.1°'],
      [0.38, 'SWF: may have tested a new sensor or payload; what and why are unclear', 'SWF: purpose and payload unclear'],
      [0.46, 'Oct. 2024: aerobraking to lower the orbit; landed at Vandenberg 7 Mar. 2025 (434 days)', 'Landed 7 Mar. 2025 after 434 days'],
      [0.51, 'OTV-8 launched 21 Aug. 2025; SWF says it was still in orbit in Feb. 2026', 'OTV-8 launched 21 Aug. 2025'],
      [0.54, 'China’s CSSHQ: flights of 2, 276 and 268 days; a fourth launched 6 Feb. 2026 (SWF)', 'CSSHQ: flights of 2, 276, 268 days'],
      [0.56, 'Flight 1 (launched 4 Sept. 2020) spent 2 days in orbit', 'CSSHQ flight 1: 2 days in orbit'],
      [0.575, 'Flight 2 (2022–23): orbit raised to' + ' ~607 × 597 km; Object J catalogued, apparently released', 'Flight 2: Object J apparently released'],
      [0.625, 'LeoLabs: RPOs with Object J, “[at] least two and possibly three capture/docking operations”', 'LeoLabs: RPOs with Object J'],
      [0.76, 'Flight 3 (2023–24): released Object G on 24 May 2024; RPOs in June, within 1 km on 12 June', 'Flight 3: Object G released 24 May 2024'],
      [
        0.86,
        'A 2019 PLA analysis (not SWF’s view): the X-37B could become an “aggressive unmanned intelligent fighter”',
        'A 2019 PLA analysis, not SWF’s view',
      ],
      [0.93, 'SWF: Chinese concern about the X-37B is thought to have driven China to build its own spaceplane', 'SWF: X-37B thought to have driven CSSHQ'],
      [0.975, 'Flight 4 launched from Jiuquan on 6 Feb. 2026; SWF reports no landing yet', 'Flight 4 launched 6 Feb. 2026'],
    ],
    cameras: [
      { name: 'Tour (auto)', auto: true, at: [40, -25, 4.4], phone: { at: [40, -25, 5.2] } },
      { name: 'X-37B: LEO flights', chip: 'X-37B LEO flights', act: 0, fitCraft: { anchor: 'us', ids: ['x37'], dir: [-0.5, 0.55, 0.7], dMin: 1.1, fill: 0.75, t: 0.15 } },
      { name: 'X-37B OTV-7: follows the craft', chip: 'X-37B OTV-7', act: 1, fitCraft: { anchor: 'heo', ids: ['x37h'], dir: [-0.6, 0.7, 0.6], dMin: 0.8, fill: 0.85, t: 0.42 } },
      {
        name: 'China: CSSHQ and released objects',
        chip: 'China CSSHQ',
        act: 2,
        fitCraft: { anchor: 'cn', ids: ['csshq', 'objJ', 'objG'], dir: [-0.3, 0.6, 0.75], fill: 0.93, dMin: 0.1, t: 0.75 },
      },
      { name: 'Wide: Earth and X-37B LEO orbits', at: [40, -25, 4.4], phone: { at: [40, -25, 5.2] }, ref: false },
    ],
    staticCenter: [40, 105],
    staticFit: 1.6,
    staticFitPhone: 1.3,
    staticSnap: { csshq: [0.6], objJ: [0.605], objG: [0.93] },
    staticLabels: { csshq: 'CSSHQ + Obj. J, G' },
    staticNoLabel: ['objJ', 'objG'], // the static key names them: one label for the China group, not three stacked on the limb
    staticCraftScale: { csshq: 0.78 },
    staticKey: [
      [C.us, 'US X-37B: LEO flights, OTV-7 orbit', 'X-37B orbits'],
      [C.geo, 'GEO ring (35,786 km)', 'GEO ring'],
      [C.cn, 'China: CSSHQ and released objects J, G', 'CSSHQ, Obj. J, G'],
    ],
    staticStatusPhone: 'X-37B: eight flights since 2010 · CSSHQ: three flights, a fourth launched Feb. 2026',
    staticStatus:
      'US X-37B: eight flights since 2010 (OTV-7 in an orbit reaching 38,838 km) · China’s CSSHQ: three flights and' + ' a fourth launched in Feb. 2026',
  },
];
export const HERO = {
  id: 'hero',
  title: 'Overview',
  shells: ['LEO', 'MEO', 'GEO'],
  duration: 40,
  spin: true,
  shellLabels: { LEO: 'LEO ≤2,000 km', MEO: 'MEO · GPS', GEO: 'GEO ~35,786 km' },
  shellShort: { LEO: 'LEO', MEO: 'MEO · GPS', GEO: 'GEO' },
  shellAng: { LEO: -58, MEO: 42, GEO: 80 },
  staticShellAng: { LEO: 150, MEO: -28, GEO: 8 },
  shellOff: { LEO: [-30, 34], MEO: [46, 22], GEO: [46, -26] },
  actors: [
    {
      type: 'ring',
      alt: 420,
      inc: 51.6,
      raan: 30,
      color: C.iss,
      sat: { phase: 0.04, speed: 3, label: 'ISS (illustrative orbit)', short: 'ISS', dx: 0, dy: 0, offGlobe: true, iss: true, big: 1.3, minPx: 46, maxPx: 72 },
    },
    { type: 'constellation', alt: 20200, inc: 55, planes: 6, per: 3, color: C.gps, speed: 0.4 },
    { type: 'ring', alt: GEO_ALT, inc: 0, raan: 0, color: C.geo, sats: 14 },
  ],
  still: 0.2,
  camDist: 7.2,
  focus: [22, -30],
  wideLat: 13,
};
